apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobook-pvc
  namespace: audiobookshelf
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
